[package]
name = "glorious-mouse-control"
version = "0.2.0"
edition = "2021"

[profile.release]
opt-level = "s"
lto = true

[dependencies]
rusb = "0.9"
clap = { version = "3.2", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
xdg = "2.4"
